// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaluteStocksAPI.DataBase;

#nullable disable

namespace SaluteStocksAPI.Migrations
{
    [DbContext(typeof(StocksContext))]
    [Migration("20220326180500_Fix")]
    partial class Fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.AnnualEarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FiscalDateEnding")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ReportedEPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("AnnualEarning");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.BalanceSheet", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ExistInApi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastApiRefresh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLocalRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Symbol");

                    b.ToTable("BalanceSheets");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.BalanceSheetAnnualReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AccumulatedDepreciationAmortizationPPE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CapitalLeaseObligations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashAndCashEquivalentsAtCarryingValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashAndShortTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CommonStockSharesOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentAccountsPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentLongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentNetReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DeferredRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FiscalDateEnding")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Goodwill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IntangibleAssetsExcludingGoodwill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Inventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Investments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongTermDebtNoncurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherNonCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherNonCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PropertyPlantEquipment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportedCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RetainedEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShortLongTermDebtTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShortTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShortTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalNonCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalNonCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalShareholderEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TreasuryStock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("BalanceSheetAnnualReport");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.BalanceSheetQuarterlyReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AccumulatedDepreciationAmortizationPPE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CapitalLeaseObligations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashAndCashEquivalentsAtCarryingValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashAndShortTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CommonStockSharesOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentAccountsPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentLongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentNetReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DeferredRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FiscalDateEnding")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Goodwill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IntangibleAssetsExcludingGoodwill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Inventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Investments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongTermDebtNoncurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherNonCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherNonCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PropertyPlantEquipment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportedCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RetainedEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShortLongTermDebtTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShortTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShortTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalNonCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalNonCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalShareholderEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TreasuryStock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("BalanceSheetQuarterlyReports");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CashFlow", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ExistInApi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastApiRefresh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLocalRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Symbol");

                    b.ToTable("CashFlows");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CashFlowAnnualReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("CapitalExpenditures")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashflowFromFinancing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashflowFromInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInCashAndCashEquivalents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInInventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInOperatingAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInOperatingLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DepreciationDepletionAndAmortization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DividendPayout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DividendPayoutCommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DividendPayoutPreferredStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FiscalDateEnding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OperatingCashFlow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentsForOperatingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentsForRepurchaseOfCommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentsForRepurchaseOfEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentsForRepurchaseOfPreferredStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromIssuanceOfCommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromIssuanceOfPreferredStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromOperatingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromRepaymentsOfShortTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromRepurchaseOfEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromSaleOfTreasuryStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProfitLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportedCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("CashFlowAnnualReport");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CashFlowQuarterlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("CapitalExpenditures")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashflowFromFinancing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashflowFromInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInCashAndCashEquivalents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInInventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInOperatingAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInOperatingLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChangeInReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DepreciationDepletionAndAmortization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DividendPayout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DividendPayoutCommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DividendPayoutPreferredStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FiscalDateEnding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OperatingCashFlow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentsForOperatingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentsForRepurchaseOfCommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentsForRepurchaseOfEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentsForRepurchaseOfPreferredStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromIssuanceOfCommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromIssuanceOfPreferredStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromOperatingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromRepaymentsOfShortTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromRepurchaseOfEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProceedsFromSaleOfTreasuryStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProfitLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportedCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("CashFlowQuarterlyReport");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CompanyOverview", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AnalystTargetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Beta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BookValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CIK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DilutedEPSTTM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DividendDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DividendPerShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EBITDA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EVToEBITDA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EVToRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExDividendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ExistInApi")
                        .HasColumnType("bit");

                    b.Property<string>("FiscalYearEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ForwardPE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrossProfitTTM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastApiRefresh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLocalRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("LatestQuarter")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MarketCapitalization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OperatingMarginTTM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PEGRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PERatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceToBookRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceToSalesRatioTTM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProfitMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QuarterlyEarningsGrowthYOY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QuarterlyRevenueGrowthYOY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReturnOnAssetsTTM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReturnOnEquityTTM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenuePerShareTTM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTTM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SharesOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TrailingPE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("_200DayMovingAverage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("_50DayMovingAverage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("_52WeekHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("_52WeekLow")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Symbol");

                    b.ToTable("CompanyOverviews");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.Earnings", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ExistInApi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastApiRefresh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLocalRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Symbol");

                    b.ToTable("Earnings");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.IncomeStatement", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ExistInApi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastApiRefresh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLocalRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Symbol");

                    b.ToTable("IncomeStatements");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.IncomeStatementAnnualReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("ComprehensiveIncomeNetOfTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostOfRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostofGoodsAndServicesSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Depreciation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DepreciationAndAmortization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ebit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ebitda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FiscalDateEnding")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GrossProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IncomeBeforeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IncomeTaxExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestAndDebtExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InvestmentIncomeNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetIncomeFromContinuingOperations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetInterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NonInterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OperatingExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OperatingIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherNonOperatingIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportedCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ResearchAndDevelopment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SellingGeneralAndAdministrative")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("IncomeStatementAnnualReport");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.IncomeStatementQuarterlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("ComprehensiveIncomeNetOfTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostOfRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostofGoodsAndServicesSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Depreciation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DepreciationAndAmortization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ebit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ebitda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FiscalDateEnding")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GrossProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IncomeBeforeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IncomeTaxExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestAndDebtExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InvestmentIncomeNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetIncomeFromContinuingOperations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetInterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NonInterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OperatingExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OperatingIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherNonOperatingIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportedCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ResearchAndDevelopment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SellingGeneralAndAdministrative")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("IncomeStatementQuarterlyReport");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.ListingRow", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelistingDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ExistInApi")
                        .HasColumnType("bit");

                    b.Property<string>("IpoDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastApiRefresh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLocalRefresh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Symbol");

                    b.ToTable("Listing");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.QuarterlyEarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("EstimatedEPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FiscalDateEnding")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ReportedEPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Surprise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SurprisePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("QuarterlyEarning");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.AnnualEarning", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.Earnings", "Earnings")
                        .WithMany("AnnualEarnings")
                        .HasForeignKey("Symbol");

                    b.Navigation("Earnings");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.BalanceSheet", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.CompanyOverview", "CompanyOverview")
                        .WithOne("BalanceSheet")
                        .HasForeignKey("SaluteStocksAPI.Models.FundamentalData.BalanceSheet", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyOverview");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.BalanceSheetAnnualReport", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.BalanceSheet", "BalanceSheet")
                        .WithMany("AnnualReports")
                        .HasForeignKey("Symbol");

                    b.Navigation("BalanceSheet");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.BalanceSheetQuarterlyReports", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.BalanceSheet", "BalanceSheet")
                        .WithMany("QuarterlyReports")
                        .HasForeignKey("Symbol");

                    b.Navigation("BalanceSheet");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CashFlow", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.CompanyOverview", "CompanyOverview")
                        .WithOne("CashFlow")
                        .HasForeignKey("SaluteStocksAPI.Models.FundamentalData.CashFlow", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyOverview");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CashFlowAnnualReport", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.CashFlow", "CashFlow")
                        .WithMany("AnnualReports")
                        .HasForeignKey("Symbol");

                    b.Navigation("CashFlow");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CashFlowQuarterlyReport", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.CashFlow", "CashFlow")
                        .WithMany("QuarterlyReports")
                        .HasForeignKey("Symbol");

                    b.Navigation("CashFlow");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.Earnings", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.CompanyOverview", "CompanyOverview")
                        .WithOne("Earnings")
                        .HasForeignKey("SaluteStocksAPI.Models.FundamentalData.Earnings", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyOverview");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.IncomeStatement", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.CompanyOverview", "CompanyOverview")
                        .WithOne("IncomeStatement")
                        .HasForeignKey("SaluteStocksAPI.Models.FundamentalData.IncomeStatement", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyOverview");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.IncomeStatementAnnualReport", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.IncomeStatement", "IncomeStatement")
                        .WithMany("AnnualReports")
                        .HasForeignKey("Symbol");

                    b.Navigation("IncomeStatement");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.IncomeStatementQuarterlyReport", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.IncomeStatement", "IncomeStatement")
                        .WithMany("QuarterlyReports")
                        .HasForeignKey("Symbol");

                    b.Navigation("IncomeStatement");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.QuarterlyEarning", b =>
                {
                    b.HasOne("SaluteStocksAPI.Models.FundamentalData.Earnings", "Earnings")
                        .WithMany("QuarterlyEarnings")
                        .HasForeignKey("Symbol");

                    b.Navigation("Earnings");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.BalanceSheet", b =>
                {
                    b.Navigation("AnnualReports");

                    b.Navigation("QuarterlyReports");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CashFlow", b =>
                {
                    b.Navigation("AnnualReports");

                    b.Navigation("QuarterlyReports");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.CompanyOverview", b =>
                {
                    b.Navigation("BalanceSheet");

                    b.Navigation("CashFlow");

                    b.Navigation("Earnings");

                    b.Navigation("IncomeStatement");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.Earnings", b =>
                {
                    b.Navigation("AnnualEarnings");

                    b.Navigation("QuarterlyEarnings");
                });

            modelBuilder.Entity("SaluteStocksAPI.Models.FundamentalData.IncomeStatement", b =>
                {
                    b.Navigation("AnnualReports");

                    b.Navigation("QuarterlyReports");
                });
#pragma warning restore 612, 618
        }
    }
}
